# Generated by Django 5.1.2 on 2024-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('features', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
