# Generated by Django 5.1.2 on 2024-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cow',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
