# Generated by Django 5.1.2 on 2024-10-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('milk_amount_total', models.FloatField()),
                ('cows_milked', models.IntegerField()),
                ('milk_amount_e', models.FloatField()),
                ('milk_amount_v', models.FloatField()),
                ('milk_amount_1', models.FloatField()),
                ('milk_fat_per', models.FloatField()),
                ('milk_prot_per', models.FloatField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lists.staff')),
            ],
        ),
    ]
